apiVersion: v2
name: nvidia-dra-driver-gpu
description: Dynamic Resource Allocation (DRA) for NVIDIA GPUs in Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

# Note(JP): no v prefix allowed
version: 25.3.0-rc.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.

# Note(JP): this currently defines the default `tag` value in a k8s
# image specification. A "v" is prefixed in our template helpers to ensure consistency.
appVersion: "25.3.0-rc.1"
