---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nvidia-dra-driver-gpu.name" . }}-clusterrole-binding
  namespace: {{ include "nvidia-dra-driver-gpu.namespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "nvidia-dra-driver-gpu.serviceAccountName" . }}
  namespace: {{ include "nvidia-dra-driver-gpu.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "nvidia-dra-driver-gpu.name" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
