---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compute-domain-daemon-role
rules:
- apiGroups: ["resource.nvidia.com"]
  resources: ["computedomains", "computedomains/status"]
  verbs: ["get", "list", "watch", "update", "patch"]

{{- $root := . -}}
{{- range $namespace := splitList "," (include "nvidia-dra-driver-gpu.namespaces" .) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compute-domain-daemon-service-account
  namespace: {{ $namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: compute-domain-daemon-role-binding-{{ $namespace }}
subjects:
- kind: ServiceAccount
  name: compute-domain-daemon-service-account
  namespace: {{ $namespace }}
roleRef:
  kind: ClusterRole
  name: compute-domain-daemon-role
  apiGroup: rbac.authorization.k8s.io
{{- if $root.Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: compute-domain-daemon-anyuid-role-binding-{{ $namespace }}
subjects:
- kind: ServiceAccount
  name: compute-domain-daemon-service-account
  namespace: {{ $namespace }}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
