{{- if .Values.resources.computeDomains.enabled }}
---
apiVersion: {{ include "nvidia-dra-driver-gpu.resourceApiVersion" . }}
kind: DeviceClass
metadata:
  name: compute-domain-daemon.nvidia.com
spec:
  selectors:
  - cel:
      expression: "device.driver == 'compute-domain.nvidia.com' && device.attributes['compute-domain.nvidia.com'].type == 'daemon'"
{{- end }}
