{{- if .Values.kubeletPlugin.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nvidia-dra-driver-gpu.name" . }}-kubelet-plugin
  namespace: {{ include "nvidia-dra-driver-gpu.namespace" . }}
  labels:
    {{- include "nvidia-dra-driver-gpu.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nvidia-dra-driver-gpu.selectorLabels" (dict "context" . "componentName" "kubelet-plugin") | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  # Some CNIs are not capable of controlling access to host network resources nor plain IP addresses,
  # as they are identity based and these resources are not being covered this way.
  #
  # Therefore, we cannot filter egress traffic by destination using native network policies and pod selectors.
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
{{- end }}
