{{- if .Values.serviceAccount.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nvidia-dra-driver-gpu.name" . }}-clusterrole-controller
rules:
- apiGroups: ["resource.nvidia.com"]
  resources: ["computedomains"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["resource.nvidia.com"]
  resources: ["computedomains/status"]
  verbs: ["update"]
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceclaimtemplates"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nvidia-dra-driver-gpu.serviceAccountName" $ }}-controller
  namespace: {{ include "nvidia-dra-driver-gpu.namespace" . }}
  labels:
    {{- include "nvidia-dra-driver-gpu.labels" $ | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nvidia-dra-driver-gpu.name" $ }}-clusterrole-binding-controller-{{ include "nvidia-dra-driver-gpu.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nvidia-dra-driver-gpu.serviceAccountName" $ }}-controller
    namespace: {{ include "nvidia-dra-driver-gpu.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "nvidia-dra-driver-gpu.name" $ }}-clusterrole-controller
  apiGroup: rbac.authorization.k8s.io

{{- range $namespace := splitList "," (include "nvidia-dra-driver-gpu.namespaces" .) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nvidia-dra-driver-gpu.name" $ }}-role-controller
  namespace: {{ $namespace }}
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nvidia-dra-driver-gpu.name" $ }}-role-binding-controller
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nvidia-dra-driver-gpu.serviceAccountName" $ }}-controller
    namespace: {{ include "nvidia-dra-driver-gpu.namespace" $ }}
roleRef:
  kind: Role
  name: {{ include "nvidia-dra-driver-gpu.name" $ }}-role-controller
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
