---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nvidia-dra-driver-gpu.name" . }}-role
  namespace: {{ include "nvidia-dra-driver-gpu.namespace" . }}
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
