# One pod, one container asking for 1 distinct GPU

---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-test-vfio

---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test-vfio
  name: single-gpu
spec:
  spec:
    devices:
      requests:
      - name: gpu
        deviceClassName: vfio.gpu.nvidia.com

---
apiVersion: v1
kind: Pod
metadata:
  namespace: gpu-test-vfiopci
  name: pod1
  labels:
    app: pod
spec:
  containers:
  - name: ctr
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["sleep 9999 & wait"]
    resources:
      claims:
      - name: gpu
  resourceClaims:
  - name: gpu
    resourceClaimTemplateName: single-gpu
