apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: k8s-dra-driver-gpu-cluster
  region: us-east-2
  version: "1.33"
availabilityZones:
  - us-east-2a
  - us-east-2b
  - us-east-2c
managedNodeGroups:
  - name: system
    amiFamily: AmazonLinux2023
    instanceType: m6g.large
    privateNetworking: true
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    labels:
      role: system
    taints:
      - key: CriticalAddonsOnly
        effect: NoSchedule
    updateConfig:
      maxUnavailable: 1
  - name: gpu
    amiFamily: AmazonLinux2023
    instanceType: g6e.4xlarge
    privateNetworking: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 4
    labels:
      role: gpu
      nvidia.com/gpu.present: "true"
    taints:
      - key: nvidia.com/gpu
        effect: NoSchedule
    updateConfig:
      maxUnavailable: 1
    overrideBootstrapCommand: |
      apiVersion: node.eks.aws/v1alpha1
      kind: NodeConfig
      spec:
        kubelet:
          config:
            featureGates:
              DynamicResourceAllocation: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
    configurationValues: |-
      nodeSelector:
        role: system
  - name: eks-pod-identity-agent
    version: latest
  - name: kube-proxy
    version: latest
iam:
  withOIDC: true