---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Namespace }}
  generateName: {{ .GenerateName }}
  finalizers:
    - {{ .Finalizer }}
  labels:
    app.kubernetes.io/name: {{ .AppLabelValue }}
    {{ .ComputeDomainLabelKey }}: {{ .ComputeDomainLabelValue }}
spec:
  selector:
    matchLabels:
      {{ .ComputeDomainLabelKey }}: {{ .ComputeDomainLabelValue }}
  template:
    metadata:
      labels:
        {{ .ComputeDomainLabelKey }}: {{ .ComputeDomainLabelValue }}
    spec:
      serviceAccountName: compute-domain-daemon-service-account
      nodeSelector:
        {{ .ComputeDomainLabelKey }}: {{ .ComputeDomainLabelValue }}
      containers:
      # Run the compute domain daemon
      - name: compute-domain-daemon
        image: {{ .ImageName }}
        command: ["compute-domain-daemon", "run"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          claims:
          - name: compute-domain-daemon
        startupProbe:
          exec:
            command: ["compute-domain-daemon", "check"]
          initialDelaySeconds: 1
          periodSeconds: 1
          timeoutSeconds: 10
          failureThreshold: 10
        livenessProbe:
          exec:
            command: ["compute-domain-daemon", "check"]
          initialDelaySeconds: 10
          periodSeconds: 5
      # Repel all node taints.
      # See https://github.com/NVIDIA/k8s-dra-driver-gpu/issues/305
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"
        - operator: "Exists"
          effect: "NoExecute"
        - operator: "Exists"
          effect: "PreferNoSchedule"
      resourceClaims:
      - name: compute-domain-daemon
        resourceClaimTemplateName: {{ .ResourceClaimTemplateName }}
