---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  namespace: {{ .Namespace }}
  name: {{ .Name }}
  finalizers:
    - {{ .Finalizer }}
  labels:
    {{ .ComputeDomainLabelKey }}: {{ .ComputeDomainLabelValue }}
    {{ .TargetLabelKey }}: {{ .TargetLabelValue }}
spec:
  spec:
    devices:
      requests:
      - name: channel
        exactly:
          deviceClassName: {{ .DeviceClassName }}
      config:
      - requests: ["channel"]
        opaque:
          driver: {{ .DriverName }}
          parameters:
            apiVersion: {{ .ChannelConfig.APIVersion }}
            kind: {{ .ChannelConfig.Kind }}
            domainID: {{ .ChannelConfig.DomainID }}
            allocationMode: {{ .ChannelConfig.AllocationMode }}
