name: tests-jp

on:
  push:
  pull_request:

jobs:
  testsuite:
    runs-on: compute-domain-runner
    steps:
      - uses: actions/checkout@v5
      - name: bats-suite
        run: |
          echo "running"
          sudo apt-get -y install time
          make bats
