name: tests

on:
  push:
  pull_request:

jobs:
  bats:
    runs-on: compute-domain-runner
    steps:
      - uses: actions/checkout@v5
      - name: make-bats
        run: |
          echo "running"
          make bats
