name: tests-jp

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/ci.yaml
    runs-on: compute-domain-runner
    steps:
      - uses: actions/checkout@v5
      - name: tests
        run: |
          echo "running"
          make bats
